# Jupyter Book 基本設定
title: 城市文資安養
author: 使用者名稱
language: zh

only_build_toc_files: true

execute:
  execute_notebooks: "off"

sphinx:
  config:
    html_theme: sphinx_book_theme
    html_logo: ""
    html_favicon: ""
