# Jupyter Book 設定檔 (_config.yml)

title: 城市文資安養
author: USER
logo: images/logo.png

only_build_toc_files: true

repository:
  url: https://github.com/brianwu989/Jupyter-Book-test1
  path_to_book: ""
  branch: gh-pages

html:
  baseurl: /Jupyter-Book-test1
  favicon: logo.png
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  extra_navbar: 製作：吳柏翰，資料來源：國網中心 LASS 資料
  extra_footer: 本網站使用 Jupyter Book 製作，並部署於 GitHub Pages。
