# Jupyter Book 設定檔 (_config.yml)

title: 城市文資安養
author: USER
logo: images/logo.png

only_build_toc_files: true

repository:
  url: https://github.com/brianwu989/Jupyter-Book-test1
  path_to_book: ""
  branch: main

html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
