name: deploy-book

on:
  push:
    branches:
      - main  # 你編輯文件的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -U jupyter-book

      - name: Build the book
        run: jb build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
